# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillLegislationSynopsis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_bill', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('synopsis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Abstain'), (3, 'Absent')], default=0)),
                ('bill_legislation_synopsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.BillLegislationSynopsis')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=54)),
                ('last_name', models.CharField(max_length=54)),
                ('email', models.EmailField(max_length=54)),
                ('district', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionLegislationSynopsis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_resolution', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('synopsis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Abstain'), (3, 'Absent')], default=0)),
                ('council_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CouncilMember')),
                ('resolution_legislation_synopsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ResolutionLegislationSynopsis')),
            ],
        ),
        migrations.AddField(
            model_name='billvoting',
            name='council_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CouncilMember'),
        ),
    ]
